version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:13-jdk-buster-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: ./gradlew -q properties
      - run: ./gradlew -q dependencies
      - run: ./gradlew --full-stacktrace check
      - run: ./gradlew --full-stacktrace shadowJar